### PR TITLE
Create Feeder Groups.md

### PR DESCRIPTION
**Pull request by surabibio**
Hi Mark, Request you to please merge this code into the wiki.

### CODE REVIEW

**Comment by markmaker** [comment]
Hi @surabibio,

First, I don't have merge rights in this repo, you would have to ask @vonnieda.

But reading the [readme](https://github.com/openpnp/scripts#readme), you should add it to the Wiki, not make a PR.

_Mark

**Comment by surabibio** [comment]
Hi Jason,

Please grant me write permission to the wiki so that I may add the scripts that are pending in the PR.

BR,

Ravi

**Comment by vonnieda** [comment]
Wiki is open to all to edit. Just click edit on the page.

Jason

**Comment by surabibio** [comment]
screen shot
I don’t seem to have write permission to edit the wiki

**Comment by surabibio** [comment]
I don’t seem to have write permission to edit the wiki.

**Comment by vonnieda** [comment]
Apologies for the delay @surabibio. I have added you to the repo and you should be able to write to it now. You may have an invitation in your Inbox.

Thanks,
Jason

**Pull request closed without merging**
